name: aziko
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  #state management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  
  #remote data
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  firebase_storage: ^11.2.2
  google_sign_in: ^6.1.3

  #local data
  shared_preferences: ^2.0.17
  #sqflite: ^2.0.2
  #path_provider: ^2.0.8

  #DI
  get_it: ^7.2.0

  # Functional programming thingies
  dartz: ^0.10.1
  equatable: ^2.0.5

  #images, gallery, video
  image_picker: ^0.8.4+8

  #svg, icon, font
  flutter_svg: 1.1.5
  google_fonts: 2.2.0
  font_awesome_flutter: ^9.2.0
  country_icons: ^2.0.2
  fluttericon: ^2.0.0

  # navigation
  go_router: ^6.0.5

  #others
  pin_code_fields: ^7.4.0
  email_validator: ^2.0.1

  #
  top_snackbar_flutter: ^3.0.0+1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_phone_field: ^3.1.0
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/png/illustrations/
    - assets/png/navbar/
    - assets/png/icons/
    - assets/images/

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
