// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz2anSKo9WEjPwoB0LHKi7mWBLWbeE_f0',
    appId: '1:484670992132:web:8ba1f15383beadf456aa51',
    messagingSenderId: '484670992132',
    projectId: 'aziko-e1628',
    authDomain: 'aziko-e1628.firebaseapp.com',
    storageBucket: 'aziko-e1628.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYqHjXTFeVns2wB1G8IFiwzV90d09KQCw',
    appId: '1:484670992132:android:eb28f739dbb965f656aa51',
    messagingSenderId: '484670992132',
    projectId: 'aziko-e1628',
    storageBucket: 'aziko-e1628.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcHHhltKmdGCBb23OonGz2Xi33tg_mq7g',
    appId: '1:484670992132:ios:bba0aebad508651656aa51',
    messagingSenderId: '484670992132',
    projectId: 'aziko-e1628',
    storageBucket: 'aziko-e1628.appspot.com',
    iosClientId: '484670992132-v2pg1q5nv9ng3oa26ig49b7uvk7at7ig.apps.googleusercontent.com',
    iosBundleId: 'com.aziko.aziko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcHHhltKmdGCBb23OonGz2Xi33tg_mq7g',
    appId: '1:484670992132:ios:bba0aebad508651656aa51',
    messagingSenderId: '484670992132',
    projectId: 'aziko-e1628',
    storageBucket: 'aziko-e1628.appspot.com',
    iosClientId: '484670992132-v2pg1q5nv9ng3oa26ig49b7uvk7at7ig.apps.googleusercontent.com',
    iosBundleId: 'com.aziko.aziko',
  );
}
